---
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('specific_deployment_identifier')}"

  version_number: "%{hiera('version_number')}"

  admin_password: "%{hiera('admin_password')}"

  peer_server_port: 7874
  api_server_port: 7876

  initial_blockchain_archive_path: "s3://%{hiera('blockchain_archive_bucket_name')}/%{hiera('blockchain_archive_key')}"

  desired_count: 1
  deployment_maximum_percent: 100
  deployment_minimum_healthy_percent: 0

  secrets_bucket_name: "%{hiera('specific_storage_bucket_name')}"

  common_state_bucket_name: "%{hiera('common_state_bucket_name')}"
  common_state_key: "%{hiera('common_state_key')}"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"

  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_key: "%{hiera('cluster_state_key')}"

  image_repository_state_bucket_name: "%{hiera('nxt_image_repository_state_bucket_name')}"
  image_repository_state_key: "%{hiera('nxt_image_repository_state_key')}"

backend_config:
  bucket: "%{hiera('nxt_service_state_bucket_name')}"
  key: "%{hiera('nxt_service_state_key')}"
  region: "%{hiera('region')}"
  encrypt: "true"
